In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5017, 4693, 8764, 6557],
 [5017, 4693, 8764, 4597],
 [5017, 4376, 8764, 444],
 [2776, 9358, 7266, 7399, 4980],
 [2776, 9358, 7266, 7399, 5417],
 [3712, 5017, 8526, 8764, 9946],
 [7929, 9535, 8200, 7399]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5017 4693 8764 6557]
 [   0    0    0    0 5017 4693 8764 4597]
 [   0    0    0    0 5017 4376 8764  444]
 [   0    0    0 2776 9358 7266 7399 4980]
 [   0    0    0 2776 9358 7266 7399 5417]
 [   0    0    0 3712 5017 8526 8764 9946]
 [   0    0    0    0 7929 9535 8200 7399]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\satishrajendranconda\Anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 75ms/step


array([[[ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [-0.03792738,  0.01958679, -0.04232483, -0.03475742,
          0.02182527,  0.01143194, -0.03125288,  0.02584182,
          0.0050171 ,  0.04725457],
        [-0.02213118,  0.00730393,  0.02797868, -0.02386508,
         -0.0024281 ,  0.04419583, -0.02011771, -0.00502002,
         -0.03373672, -0.04126013],
        [-0.02629154,  0.02487988, -0.02824695,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5017, 4693, 8764, 6557])

In [14]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 256ms/step


array([[ 0.00643842,  0.03621011,  0.04130046, -0.00480251,  0.04173969,
        -0.02359104, -0.00651431, -0.04240527,  0.00952165,  0.04131707],
       [ 0.00643842,  0.03621011,  0.04130046, -0.00480251,  0.04173969,
        -0.02359104, -0.00651431, -0.04240527,  0.00952165,  0.04131707],
       [ 0.00643842,  0.03621011,  0.04130046, -0.00480251,  0.04173969,
        -0.02359104, -0.00651431, -0.04240527,  0.00952165,  0.04131707],
       [ 0.00643842,  0.03621011,  0.04130046, -0.00480251,  0.04173969,
        -0.02359104, -0.00651431, -0.04240527,  0.00952165,  0.04131707],
       [ 0.04046268, -0.01989275, -0.01600838, -0.01728903, -0.00932206,
        -0.03708712,  0.04265716, -0.0246699 ,  0.03498015, -0.01122134],
       [-0.04302886,  0.02787782, -0.00319532, -0.01368185,  0.00408836,
        -0.04117782,  0.0338655 ,  0.03574247,  0.0474431 ,  0.02203474],
       [ 0.04476443,  0.00847448, -0.0076547 , -0.01855131,  0.01486827,
        -0.029093  , -0.03079541,  0.02548406